#QCA SND CARD
snd-soc-ipq40xx-objs := ipq40xx.o ipq40xx-wcd.o
snd-soc-ipq40xx-pcm-i2s-objs := ipq40xx-pcm-i2s.o
snd-soc-ipq40xx-pcm-tdm-objs := ipq40xx-pcm-tdm.o
snd-soc-ipq40xx-pcm-spdif-objs := ipq40xx-pcm-spdif.o
snd-soc-ipq40xx-codec-objs := ipq40xx-codec.o
snd-soc-ipq40xx-cpu-dai-objs := ipq40xx-cpu-dai.o
snd-soc-ipq40xx-pcm-raw-objs := ipq40xx-pcm-raw.o ipq40xx-pcm-raw-lb-test.o

obj-$(CONFIG_SND_QCA_SOC_IPQ40XX) += snd-soc-ipq40xx.o
obj-$(CONFIG_SND_IPQ40XX_SOC_PCM_I2S) += snd-soc-ipq40xx-pcm-i2s.o
obj-$(CONFIG_SND_IPQ40XX_SOC_PCM_TDM) += snd-soc-ipq40xx-pcm-tdm.o
obj-$(CONFIG_SND_IPQ40XX_SOC_PCM_SPDIF) += snd-soc-ipq40xx-pcm-spdif.o
obj-$(CONFIG_SND_IPQ40XX_SOC_CODEC) += snd-soc-ipq40xx-codec.o
obj-$(CONFIG_SND_IPQ40XX_SOC_CPU_DAI) += snd-soc-ipq40xx-cpu-dai.o
obj-$(CONFIG_SND_IPQ40XX_SOC_MBOX) += ipq40xx-mbox.o
obj-$(CONFIG_SND_IPQ40XX_SOC_ADSS) += ipq40xx-adss.o
obj-$(CONFIG_SND_IPQ40XX_SOC_STEREO) += ipq40xx-stereo.o
obj-$(CONFIG_SND_IPQ40XX_SOC_PCM_RAW) += snd-soc-ipq40xx-pcm-raw.o
